"""Auto migration

Revision ID: 0dda3a9f7cbb
Revises: 
Create Date: 2026-06-04 06:03:47.983474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dda3a9f7cbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('width', sa.Integer(), nullable=False, comment='Frame width in pixels'),
    sa.Column('height', sa.Integer(), nullable=False, comment='Frame height in pixels'),
    sa.Column('fps', sa.Float(), nullable=False, comment='Nominal frame rate of the video source'),
    sa.Column('duration_seconds', sa.Float(), nullable=False, comment='Total playback duration in seconds'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='Human-readable label for operational identification'),
    sa.Column('storage_key', sa.String(), nullable=False, comment='Object storage path for Video artifact'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_videos_storage_key', 'videos', ['storage_key'], unique=True)
    op.create_table('estimations',
    sa.Column('video_id', sa.Integer(), nullable=False, comment='Foreign key referencing the source video record'),
    sa.Column('requested_width', sa.Integer(), nullable=False, comment='Target frame width in pixels applied during preprocessing'),
    sa.Column('requested_height', sa.Integer(), nullable=False, comment='Target frame height in pixels applied during preprocessing'),
    sa.Column('requested_fps', sa.Float(), nullable=False, comment='Frame sampling rate applied before inference in fps'),
    sa.Column('skip_start_seconds', sa.Float(), nullable=False, comment='Temporal offset in seconds to skip from video start before processing'),
    sa.Column('duration_seconds', sa.Float(), nullable=False, comment='Total analyzed segment duration in seconds'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='Human-readable label for operational identification'),
    sa.Column('storage_key', sa.String(), nullable=False, comment='Object storage path for Estimation artifact'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_estimations_storage_key', 'estimations', ['storage_key'], unique=True)
    op.create_index('ix_estimations_video_id', 'estimations', ['video_id'], unique=False)
    op.create_table('visualizations',
    sa.Column('estimation_id', sa.Integer(), nullable=False, comment='Foreign key referencing the source pose analysis record'),
    sa.Column('show_bbox', sa.Boolean(), nullable=False, comment='Flag indicating whether bounding boxes were rendered'),
    sa.Column('show_keypoints', sa.Boolean(), nullable=False, comment='Flag indicating whether 2D keypoint markers were overlaid'),
    sa.Column('show_skeleton', sa.Boolean(), nullable=False, comment='Flag indicating whether skeletal connections were drawn'),
    sa.Column('show_bbox_confidence', sa.Boolean(), nullable=False, comment='Flag indicating whether confidence scores were rendered near bounding boxes'),
    sa.Column('crf', sa.Integer(), nullable=False, comment='Constant Rate Factor for x264 encoding. Lower values increase quality and file size.'),
    sa.Column('preset', sa.String(length=16), nullable=False, comment='x264 speed vs compression preset. Affects encoding time and final file size.'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key identifier'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='Human-readable label for operational identification'),
    sa.Column('storage_key', sa.String(), nullable=False, comment='Object storage path for Visualization artifact'),
    sa.ForeignKeyConstraint(['estimation_id'], ['estimations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visualizations_estimation_id', 'visualizations', ['estimation_id'], unique=False)
    op.create_index('ix_visualizations_storage_key', 'visualizations', ['storage_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visualizations_storage_key', table_name='visualizations')
    op.drop_index('ix_visualizations_estimation_id', table_name='visualizations')
    op.drop_table('visualizations')
    op.drop_index('ix_estimations_video_id', table_name='estimations')
    op.drop_index('ix_estimations_storage_key', table_name='estimations')
    op.drop_table('estimations')
    op.drop_index('ix_videos_storage_key', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
